//**************************************
// Generated by mcpp translator
// Version 1.3
//**************************************

#ifndef __DMSTOPODATA_M_H__
#define __DMSTOPODATA_M_H__

#include"mcode/mvector.h"
#include"mcode/mstring.h"
#include"mcode/mstream.h"
#include"mcode/mclient.h"
#include"public_m.h"


struct TRequestDmsTopo
{
	int	req_id;
	MLang::VECTOR<MLang::Long>	vec_key;
	TRequestDmsTopo();
	TRequestDmsTopo(const TRequestDmsTopo&);
	TRequestDmsTopo&operator=(const TRequestDmsTopo&);
	void __write(MLang::OutputStream&__os)const;
	void __read(MLang::InputStream&__is);
};
struct TRespondDmsTopo
{
	int	req_id;
	int	resp_code;
	MLang::STRING	resp_msg;
	MLang::VECTOR<MLang::Long>	rep_key;
	TRespondDmsTopo();
	TRespondDmsTopo(const TRespondDmsTopo&);
	TRespondDmsTopo&operator=(const TRespondDmsTopo&);
	void __write(MLang::OutputStream&__os)const;
	void __read(MLang::InputStream&__is);
};
#endif
