//**************************************
// Generated by mcpp translator
// Version 1.3
//**************************************

#include"DmsTopoData_m.h"
#include<assert.h>
void
TRequestDmsTopo::__write(MLang::OutputStream&__os)const
{
	__os.write_int(req_id);
	size_t len_0=vec_key.size();
	__os.write_uint(len_0);
	//for(size_t i_0=0;i_0<len_0;i_0++)
	if(len_0>0)
	{
		__os.write_long_array(&vec_key[0],len_0);
		//break;
	}
}
void
TRequestDmsTopo::__read(MLang::InputStream&__is)
{
	req_id=__is.read_int();
	size_t len_0=__is.read_uint();
	vec_key.resize(len_0);
	//for(size_t i_0=0;i_0<len_0;i_0++)
	if(len_0>0)
	{
		__is.read_long_array(&vec_key[0],len_0);
		//break;
	}
}
TRequestDmsTopo::TRequestDmsTopo()
{
}
TRequestDmsTopo::TRequestDmsTopo(const TRequestDmsTopo&__val)
:req_id(__val.req_id),vec_key(__val.vec_key)
{

}
TRequestDmsTopo&
TRequestDmsTopo::operator=(const TRequestDmsTopo&__val)
{
	if(this == &__val)
		return *this;
	req_id=__val.req_id;
	vec_key=__val.vec_key;

	return *this;
}
void
TRespondDmsTopo::__write(MLang::OutputStream&__os)const
{
	__os.write_int(req_id);
	__os.write_int(resp_code);
	__os.write_string(resp_msg.c_str());
	size_t len_0=rep_key.size();
	__os.write_uint(len_0);
	//for(size_t i_0=0;i_0<len_0;i_0++)
	if(len_0>0)
	{
		__os.write_long_array(&rep_key[0],len_0);
		//break;
	}
}
void
TRespondDmsTopo::__read(MLang::InputStream&__is)
{
	req_id=__is.read_int();
	resp_code=__is.read_int();
	resp_msg=__is.read_string();
	size_t len_0=__is.read_uint();
	rep_key.resize(len_0);
	//for(size_t i_0=0;i_0<len_0;i_0++)
	if(len_0>0)
	{
		__is.read_long_array(&rep_key[0],len_0);
		//break;
	}
}
TRespondDmsTopo::TRespondDmsTopo()
{
}
TRespondDmsTopo::TRespondDmsTopo(const TRespondDmsTopo&__val)
:req_id(__val.req_id),resp_code(__val.resp_code),resp_msg(__val.resp_msg),rep_key(__val.rep_key)
{

}
TRespondDmsTopo&
TRespondDmsTopo::operator=(const TRespondDmsTopo&__val)
{
	if(this == &__val)
		return *this;
	req_id=__val.req_id;
	resp_code=__val.resp_code;
	resp_msg=__val.resp_msg;
	rep_key=__val.rep_key;

	return *this;
}
